services:
  postgres:
    image: postgres:16-alpine
    container_name: ttt-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: tictactoe
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
